# Generated by Django 4.1.2 on 2022-10-15 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_booking_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='long',
        ),
        migrations.AlterField(
            model_name='booking',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
