# Generated by Django 4.1.2 on 2022-10-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_lat_remove_booking_long_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_actual',
            field=models.BooleanField(default=True),
        ),
    ]
