# Generated by Django 4.1.2 on 2022-10-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_time_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hours',
            field=models.DateTimeField(null=True),
        ),
    ]
