# Generated by Django 4.1.2 on 2022-10-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_booking_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='hours',
            field=models.TimeField(null=True),
        ),
    ]
