# Generated by Django 4.1.2 on 2022-10-15 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0005_remove_machine_number_actual_order'),
        ('booking', '0008_alter_booking_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='machine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='machine.machine'),
            preserve_default=False,
        ),
    ]
