# Generated by Django 4.1.2 on 2022-10-14 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park', models.CharField(max_length=200)),
                ('characters', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('is_free', models.BooleanField(default=True)),
                ('next_order_time', models.DateTimeField()),
                ('number_actual_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.booking')),
            ],
            options={
                'db_table': 'Machine',
            },
        ),
    ]
