# Generated by Django 4.1.2 on 2022-10-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
