# Generated by Django 4.1.2 on 2022-10-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_machine_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='long',
            field=models.FloatField(blank=True),
        ),
    ]
