# Generated by Django 4.1.2 on 2022-10-15 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0003_alter_machine_lat_alter_machine_long'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='long',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='next_order_time',
        ),
    ]
