# Generated by Django 4.1.2 on 2022-10-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_remove_machine_lat_remove_machine_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='number_actual_order',
        ),
    ]
